name: Ci workflow

on:
  push:
    branches:
      - main

env:
  NODE_ENV: 22.0.0

jobs:
  echo_helloworld:
    runs-on: ubuntu-latest
    name: echo helloworld
    steps:
      - name: echo
        run: echo "hello world"

  unit_test:
    runs-on: ubuntu-latest
    name: unit test
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_ENV }}
      - name: test
        run: npm run lint

  notify:
    runs-on: ubuntu-latest
    name: Notify
    steps:
          - name: echo
            run: echo "hello world"
